version: 0.2

phases:
  install:
    commands:
      - yarn
  pre_build:
    commands:
      - NODE_ENV=$STAGE
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo $IMAGE_TAG > version.txt
      - yarn build
artifacts:
    files:
      - 'dist/**/*'
cache:
    paths:
      - 'node_modules'
