version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run lint

      - npm run test:app -- --coverage
      - bash <(curl -s https://codecov.io/bash) -c -F app -s coverage/app

      - npm run test:server -- --coverage
      - bash <(curl -s https://codecov.io/bash) -c -F server -s coverage/server

      - npm run test:shared -- --coverage
      - bash <(curl -s https://codecov.io/bash) -c -F shared -s coverage/shared
cache:
    paths:
      - 'node_modules'
