version: 0.2

phases:
  install:
    commands:
      - npm install --no-optional
  build:
    commands:
      - npm run lint
      - npm run test:coverage
  post_build:
    commands:
      - curl -s https://codecov.io/bash | bash -s - -F shared -s coverage/shared -t $CODECOV_TOKEN
      - curl -s https://codecov.io/bash | bash -s - -F server -s coverage/server -t $CODECOV_TOKEN
      - curl -s https://codecov.io/bash | bash -s - -F app -s coverage/app -t $CODECOV_TOKEN
cache:
    paths:
      - 'node_modules'
