version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(cat version.txt)
      - NODE_ENV=$STAGE
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"koa-react-%s","imageUri":"%s"}]' $NODE_ENV $REPOSITORY_URI:$IMAGE_TAG > $NODE_ENV-imagedefinitions.json
artifacts:
    files: $NODE_ENV-imagedefinitions.json
cache:
  path: /var/lib/docker
