version: 0.2

phases:
  install:
    commands:
      - yarn
  build:
    commands:
      - yarn lint
      - yarn test
  post_build:
    commands:
      - curl -s https://codecov.io/bash | bash -s - -t $CODECOV_TOKEN
cache:
    paths:
      - 'node_modules'
