version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run lint
      - npm test -- --coverage
  post_build:
    commands:
      - curl -s https://codecov.io/bash | bash -s - -t $CODECOV_TOKEN
cache:
    paths:
      - 'node_modules'
