version: 0.2

phases:
  pre_build:
    commands:
      - yarn
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - yarn lint
      - yarn test
  build:
    commands:
      - echo $IMAGE_TAG > version.txt
      - yarn build
artifacts:
    files:
      - 'dist/**/*'
cache:
    paths:
      - 'node_modules'
